### ISSUE TITLE
Parent selector inside of :not() isn't expanded out  

### ISSUE THREAD

**Issue by craigsssmith** [sass/sass#1464]
Given the following SCSS

``` scss
.baz {
  *:not(&) {
    color: blue;
  }
}
```

I would expect the following output:

``` css
.baz *:not(.baz) {
  color: blue;
}
```

However, the parent selector isn't expanded, giving:

``` css
.baz *:not(&) {
  color: blue;
}
```

What's more, if this is combined with a single usage of @extend then SASS throws an error – even when the extend is entirely separate. For example:

``` scss
.foo {
  color: red;
}
.bar {
  @extend .foo;
}
.baz {
  *:not(&) {
    color: blue;
  }
}
```

As of 3.4, this triggers the following error:

```
NoMethodError: undefined method `specificity' for &:Sass::Selector::Parent
```

**Comment by JawsomeJason** [comment]
as of this 3.4.6, `a:hover:not(.active)` throws the same error all by itself.  Had to revert back to 3.4.5.

**Comment by RajRoR** [comment]
:+1:  @thejase By reverting to version 3.4.5 from 3.4.6 worked for me too.

**Comment by jgelens** [comment]
Same problem here, reverting fixed the issue.

**Comment by manuel-colmenero** [comment]
I got bitten by this bug too, but how is it closed? Reverting to an older version is _not_ fixing the issue, this should definitely be addressed in the next version of Sass!

**Comment by MimoBerlino** [comment]
You need to have these versions together:

gem install sass --version 3.2.18
gem install compass --version 0.12.2

**Comment by hidanielle** [comment]
just got this error on `a:not(.class-name)` by itself - reverting back to 3.4.5 fixed the issue

**Comment by Kerrick** [comment]
I was also bitten by simply having `selector:not(.classname)` on 3.4.6, and reverting to 3.4.5 fixed for me too.

**Comment by coryschires** [comment]
Same here. Reverting to 3.4.5 fixed.

**Comment by JawsomeJason** [comment]
@nex3 Can we please re-open this issue?

**Comment by klaver** [comment]
Duplicate of issue #1476 ?
https://github.com/sass/sass/issues/1476

**Comment by hinok** [comment]
3.4.8 has also this issue

A way to fix it (temporary solution)

```
.test {
    &:not(#{&}--active) &__summaries:hover + &__inner {
        color: blue;
    }
}
```

**Comment by nex3** [comment]
@hinok this should be fixed as of 3.4.7. can you provide a code example the demonstrates the problem?

**Comment by hinok** [comment]
![zrzut ekranu 2015-01-17 o 04 10 51](https://cloud.githubusercontent.com/assets/1313605/5787436/f2a2eca0-9dfe-11e4-8607-19da28c558fe.png)

I use compass + sass-globbing + sass (3.4.9) now and code below:

```
&:not(&--active) &__summaries:hover + &__inner {
        color: blue;
}
```

returns error while compiling:

```
directory dist/assets/css/admin

    write dist/assets/css/admin/base.css

    error src/assets/sass/admin/modules.scss (/Users/hinok/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sass-3.4.9/lib/sass/selector/abstract_sequence.rb:96:in `block in _specificity': undefined method `specificity' for &--active:Sass::Selector::Parent)

Compilation failed in 1 files.


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error:     error src/assets/sass/admin/modules.scss (/Users/hinok/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sass-3.4.9/lib/sass/selector/abstract_sequence.rb:96:in `block in _specificity': undefined method `specificity' for &--active:Sass::Selector::Parent)
Compilation failed in 1 files.
```

**Comment by nex3** [comment]
[I can't reproduce that error](http://sassmeister.com/gist/a3d148dde158113e5158). I don't see the error in your screenshot, either.

**Comment by hinok** [comment]
@nex3 You're right that on sass-meister that error is not thrown but on my computer it is.
Anyway even if on sass-meister there is no error compilation, final compiled CSS is still not as expected

Compiled

```
.foo:not(&--active) .foo__summaries:hover + .foo__inner {
    color: blue;
}
```

Expected

```
.foo:not(.foo--active) .foo__summaries:hover + .foo__inner {
    color: blue;
}
```

This is how it looks on my computer
![error](https://cloud.githubusercontent.com/assets/1313605/5789263/b8455592-9e63-11e4-8154-4bf7faf2a5e2.gif)

**Comment by nex3** [comment]
@hinok If you can't reproduce your error on SassMeister, I can't do much to help you.

> Compiled
> 
> ``` css
> .foo:not(&--active) .foo__summaries:hover + .foo__inner {
>     color: blue;
> }
> ```
> 
> Expected
> 
> ``` css
> .foo:not(.foo--active) .foo__summaries:hover + .foo__inner {
>     color: blue;
> }
> ```

This I can do something about.

**Comment by hinok** [comment]
@nex3 Compiled and Expected results are from sass-meister.com
![zrzut ekranu 2015-01-23 o 23 17 31](https://cloud.githubusercontent.com/assets/1313605/5883831/4c84ddd0-a356-11e4-93cb-b64ab3ce4268.png)

I cannot reproduce only that strange error while compiling my project (look gif).

**Comment by cweiske** [comment]
Relevant Debian bug for jessie, which ships 3.4.6: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=788937
