### ISSUE TITLE
Sass --watch doesn't find anything, not compiling

### ISSUE THREAD

**Issue by alexmngn** [sass/sass#719]
I'm trying to use SASS but I got some issue with it, is not compiling anything. I tried different things to troubleshoot, is still not working.

Ruby 1.8.7
Sass 3.2.7
Mac OS X 10.8.3

What I try:

Install Ruby 2.0.0
Uninstall Sass
Reinstall Sass
Install the gem "listen"
Since I installed the gem "listen", I got this issue when I'm using the command sass --watch myfolder

```
>>> Sass is watching for changes. Press Ctrl-C to stop.
[Listen warning]:
Listen::MultiListener is deprecated, please use Listen::Listener instead.
```

Any idea?

Thanks. 
Alexis.

**Comment by nex3** [comment]
What is the contents of `myfolder`?

**Comment by alexmngn** [comment]
Just a *.scss file.

**Comment by nex3** [comment]
Sass compiles `.sass` files to `.css`. It won't do anything to plain `.css` files.

**Comment by alexmngn** [comment]
Edited.

**Comment by ahmedelgabri** [comment]
having the same issue

```
sass --watch css/scss/main.scss:css/main.css                                                  
>>> Sass is watching for changes. Press Ctrl-C to stop.
[Listen warning]:
Listen::MultiListener is deprecated, please use Listen::Listener instead.
```

**Comment by athaeryn** [comment]
Same issue. I think the problem was `listen-1.0.2`. I was having the problem on my work computer but not my personal one. My personal one had `listen (0.7.3)` while my work one had `listen (1.0.2, 0.7.3)`. Removing `1.0.2` got things working on my work computer again.

**Comment by athaeryn** [comment]
Could this be as simple as changing `MultiListener` to `Listener` on line 266 of sass/lib/sass/plugin/compiler.rb?

**Comment by nex3** [comment]
> Could this be as simple as changing `MultiListener` to `Listener` on line 266 of sass/lib/sass/plugin/compiler.rb?

Can someone try this and report whether it works?

**Comment by athaeryn** [comment]
I'm trying it but having some trouble building the gem...

Just swapping it out and running `rake` passes all tests though.

I could be doing something wrong though, I'm not super familiar with serious gem development...

**Comment by mgol** [comment]
@athaeryn, your fork breaks the `--sourcemap` option.

**Comment by mgol** [comment]
I've tried changing `MultiListener` to `Listener` and the warning disappears but watch still doesn't fire. My output:

```
$ sass --compass --sourcemap --watch . 
>>> Sass is watching for changes. Press Ctrl-C to stop.
  overwrite ./styles/print.css
  overwrite ./styles/print.css.map
WARNING: Couldn't determine public URL for "sprite/*.png" while generating sourcemap.
  Without a public URL, there's nothing for the source map to link to.
  Custom importers should define the #public_url method.

  overwrite ./styles/screen.css
  overwrite ./styles/screen.css.map
$ 
```

It just compiles once and that's all... Updating the listen submodule to 1.0.3 after making this change doesn't help either.

**Comment by mgol** [comment]
This is my branch: https://github.com/mzgol/sass/tree/719_MultiListener

**Comment by mgol** [comment]
BTW, I guess the major problem here is SASS picks up the globally installed listen instead of preferring its local copy...

**Comment by jaredbeck** [comment]
As a workaround, downgrading `listen` worked for me.

```
gem uninstall listen -v 1.0.3
gem install listen -v 0.7.3
```

**Comment by ya7ya** [comment]
@jaredbeck the downgrading worked for me , Thanks for the Tip :+1:

**Comment by athaeryn** [comment]
Yeah, that's a workaround, but it would be nice to fix the real issue and have sass use its own copy of listen, as @mzgol mentioned. Some people might not be able to uninstall listen-1.0.3 without breaking other things.

**Comment by cat-topanga** [comment]
Was using Linux Mint new install with Ruby 1.9.3 .
sass did compile but exited right afterwards with the Listener deprecated thing.
Downgrading worked here too so thanks,

**Comment by ahmedelgabri** [comment]
The workaround works if you are not using any other gems that depends on Listen 1.0.3 for example if you are using Guard 1.8.0 this might be a problem.

```
guard-1.8.0 depends on listen (>= 1.0.0)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]
```

**Comment by 18601673727** [comment]
@jaredbeck thanks a lot !

**Comment by nex3** [comment]
> _@mzgol wrote:_
> BTW, I guess the major problem here is SASS picks up the globally installed listen instead of preferring its local copy...

This is the intended behavior.

I'll work on getting Sass compatible with listen >= 1.0.0.

**Comment by nex3** [comment]
It looks like listen 1.0.0 has some serious bugs/feature regressions (guard/listen#111 and guard/listen#112) that make it difficult to make it compatible with Sass without drastically increasing the surface area of our integration code. As such, for now I'm going to make Sass compatible only with listen 0.7.x.

**Comment by mgol** [comment]
If SASS wants to hold onto the older listen, it really needs to not just use the default one. Now every time I update my gems, SASS breaks and I have to revert listen. Some packages might depend on listen >= 1.0 which makes them impossible to be used in the system at the same time as SASS... This is a big problem IMO.

**Comment by varemenos** [comment]
> If SASS wants to hold onto the older listen, it really needs to not just use the default one. Now every time I update my gems, SASS breaks and I have to revert listen. Some packages might depend on listen >= 1.0 which makes them impossible to be used in the system at the same time as SASS... This is a big problem IMO.

:+1:

**Comment by chriseppstein** [comment]
Our listen dependency should be declared in our gemspec so that the version can be resolved correctly by tools like bundler. Also, @nex3, what is needed to support the more recent API? Is there an issue tracking that?

**Comment by nex3** [comment]
bea480bd6b70ffd8f41ec75dfecb3e922d2ebe85, which closed the issue, makes sure Sass stable won't load listen >= 1.0. 47381156165c00870099b227d675b6b4f64dd7dc stops bundling it on master, and declares a version constraint that excludes listen >= 1.0. There should be no way to use the wrong listen version now.

@chriseppstein guard/listen#112 has been fixed, but guard/listen#111 is still blocking our use of listen.

**Comment by mgol** [comment]
Well, am I using it wrong? I have the `/DIR/sass/bin` directory from this repository added to path and I still get an error:

```
$ sass --compass --sourcemap --watch . --trace
>>> Sass is watching for changes. Press Ctrl-C to stop.
/DIR/sass/bin/../lib/sass/plugin/compiler.rb:229:in `watch': uninitialized constant Listen::MultiListener (NameError)
    from /DIR/sass/bin/../lib/sass/plugin.rb:107:in `send'
    from /DIR/sass/bin/../lib/sass/plugin.rb:107:in `method_missing'
    from /DIR/sass/bin/../lib/sass/exec.rb:482:in `watch_or_update'
    from /DIR/sass/bin/../lib/sass/exec.rb:324:in `process_result'
    from /DIR/sass/bin/../lib/sass/exec.rb:41:in `parse'
    from /DIR/sass/bin/../lib/sass/exec.rb:21:in `parse!'
    from /DIR/sass/bin/sass:9
```

I have both listen 1.1.3 and 0.7.2 installed.

**Comment by nex3** [comment]
Are you using the master branch? Currently it only declares its dependencies in the gemspec, so if you're running from the repo it might activate listen 1.x.

Chris is working on adding compatibility with 1.x, so we'll probably just do that rather than try to add a runtime gem version constraint in master.

**Comment by mgol** [comment]
Yeah, that was the master branch. OK, since compatibility with 1.x is planned, I'll just live with it, it's temporary after all.

**Comment by mgol** [comment]
I build and installed the gem to try to use it as intended but then current master doesn't work with either stable or bleeding-edge compass. :( SASS can't find Compass 0.12.2 at all and with the version from master there's listen version conflict (0.7.3 vs. 1.0.0):

```
/Library/Ruby/Site/1.8/rubygems/specification.rb:774:in `activate_dependencies': can't satisfy 'listen (~> 1.0.0)', already activated 'listen-0.7.3' (Gem::LoadError)
    from /Library/Ruby/Site/1.8/rubygems/specification.rb:766:in `each'
    from /Library/Ruby/Site/1.8/rubygems/specification.rb:766:in `activate_dependencies'
    from /Library/Ruby/Site/1.8/rubygems/specification.rb:750:in `activate'
    from /Library/Ruby/Site/1.8/rubygems.rb:1232:in `gem'
    from /usr/local/bin/compass:22
```

Is there anyway to bypass that? I need SASS, Compass & source map support which is hard to do in this situation.

Are there any time frames for releasing SASS 0.3.3 stable?

**EDIT**: I guess that's related to #764?

**EDIT2**: if anyone has a similar problem, SASS from commit c2ce041 works with stable Compass

**Comment by chriseppstein** [comment]
I'm working on the listen issue. I have pull request open for sass and a
patch in progress for compass.

On Mon, Jun 3, 2013 at 1:32 PM, Michał Gołębiowski <notifications@github.com

**Comment by jcldavid** [comment]
any progress? I'm pulling `guard` from github and i'm having version conflicts:

```
Bundler could not find compatible versions for gem "listen":
  In Gemfile:
    guard (>= 0) x86-mingw32 depends on
      listen (>= 1.0.0) x86-mingw32

    sass (= 3.3.0.alpha.149) x86-mingw32 depends on
      listen (0.7.3)
```

**Comment by bennidhamma** [comment]
I just installed a new laptop with Ubuntu 13.10 out of the box and get this error. Can someone please explain what the proper fix is I need to make? I downgraded listen to 0.7, but then I think a different package updated it again, and broke sass a second time.

**Comment by bennidhamma** [comment]
can grunt watch a directory of sass source files and create the css as I
save my files?

On Thu, Dec 12, 2013 at 3:00 AM, vohof notifications@github.com wrote:

> Use grunt, it's much faster.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nex3/sass/issues/719#issuecomment-30406732
> .

## 

ben

**Comment by mgol** [comment]
@bennidhamma Yes. See README for grunt-contrib-sass (or grunt-contrib-compass if you also use compass).

**Comment by bennidhamma** [comment]
OK will do thanks guys.

**Comment by monuzira** [comment]
Hello ,please help me.My .scss file is not working.What can be issue.

**Comment by nishantkumar155** [comment]
Hello please help me i was using this command to compile sass 
[ sass --watch saas/style.scss:stylesheets/style.css] but i am getting below error message 

>>> Sass is watching for changes. Press Ctrl-C to stop.
      error No such file or directory @ rb_sysopen - saas/style.scss

**Comment by serter95** [comment]
Hello, I am from Venezuela and i have this error:

serter@serter-VIT-P2400:/var/www/html/opencharity/src/css$ sass --watch index.scss:index.css

>>> Sass is watching for changes. Press Ctrl-C to stop.

FATAL: Listen error: unable to monitor directories for changes.

Visit https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers for info on how to fix this.

serter@serter-VIT-P2400:/var/www/html/opencharity/src/css$ 

Any Idea how to solve it?

it is the first time that hapend to me

**Comment by serter95** [comment]
I solved runnig this commad

echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

i hope that help someone

**Comment by yousephzidan** [comment]
> I solved runnig this commad
> 
> echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
> 
> i hope that help someone

Thanks this worked!
